In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
%config InlineBackend.figure_format = 'svg'
import seaborn as sns

In [6]:
rays_df = pd.read_csv("rays 2018.csv")
data.head(5)

,Gm#,Date,Unnamed: 2,Tm,Unnamed: 4,Opp,W/L,R,RA,Inn,...,Rank,GB,Win,Loss,Save,Time,D/N,Attendance,Streak,Orig. Scheduled
0,1,Thursday Mar 29,boxscore,TBR,NaN,BOS,W,6,4,NaN,...,1,Tied,Pruitt,Smith,Colome,3:00,D,31042.0,+,NaN
1,2,Friday Mar 30,boxscore,TBR,NaN,BOS,L,0,1,NaN,...,3,1.0,Price,Roe,Kimbrel,2:46,N,19203.0,-,NaN
2,3,Saturday Mar 31,boxscore,TBR,NaN,BOS,L,2,3,NaN,...,4,1.0,Porcello,Kittredge,Kimbrel,3:21,N,17838.0,--,NaN
3,4,Sunday Apr 1,boxscore,TBR,NaN,BOS,L,1,2,NaN,...,5,2.0,Velazquez,Alvarado,Kelly,3:24,D,14256.0,---,NaN
4,5,Tuesday Apr 3,boxscore,TBR,@,NYY,L,4,11,NaN,...,4,3.5,Kahnle,Pruitt,NaN,3:29,D,46776.0,----,NaN

In [8]:
rays_df.columns

Index(['Gm#', 'Date', 'Unnamed: 2', 'Tm', 'Unnamed: 4', 'Opp', 'W/L', 'R',
       'RA', 'Inn', 'W-L', 'Rank', 'GB', 'Win', 'Loss', 'Save', 'Time', 'D/N',
       'Attendance', 'Streak', 'Orig. Scheduled'],
      dtype='object')

In [11]:
rays_df.rename(columns={'Unnamed: 4': 'is away', 'R': 'Runs scored', 'RA': 'Runs allowed'}, inplace=True)
rays_df.columns

Index(['Gm#', 'Date', 'Unnamed: 2', 'Tm', 'is away', 'Opp', 'W/L',
       'Runs scored', 'Runs allowed', 'Inn', 'W-L', 'Rank', 'GB', 'Win',
       'Loss', 'Save', 'Time', 'D/N', 'Attendance', 'Streak',
       'Orig. Scheduled'],
      dtype='object')

In [12]:
cols_to_keep = ['Gm#', 'Date', 'Tm', 'is away', 'Opp', 'W/L', 'Runs scored', 'Runs allowed', 'W-L', 'Rank', 'GB', 'Time', 'D/N', 'Attendance', 'Streak']

# def clean_team_data(data):
#     df.drop('U')

In [13]:
cleaned_rays_df = rays_df[cols_to_keep]
cleaned_rays_df

,Gm#,Date,Tm,is away,Opp,W/L,Runs scored,Runs allowed,W-L,Rank,GB,Time,D/N,Attendance,Streak
0,1,Thursday Mar 29,TBR,NaN,BOS,W,6,4,1-0,1,Tied,3:00,D,31042.0,+
1,2,Friday Mar 30,TBR,NaN,BOS,L,0,1,1-1,3,1.0,2:46,N,19203.0,-
2,3,Saturday Mar 31,TBR,NaN,BOS,L,2,3,1-2,4,1.0,3:21,N,17838.0,--
3,4,Sunday Apr 1,TBR,NaN,BOS,L,1,2,1-3,5,2.0,3:24,D,14256.0,---
4,5,Tuesday Apr 3,TBR,@,NYY,L,4,11,1-4,4,3.5,3:29,D,46776.0,----
5,6,Wednesday Apr 4,TBR,@,NYY,L,2,7,1-5,4,4.0,2:44,D,40028.0,-----
6,7,Thursday Apr 5,TBR,@,BOS,L-wo,2,3,1-6,5,5.0,3:55,D,36134.0,------
7,8,Saturday Apr 7,TBR,@,BOS,L,3,10,1-7,5,6.0,2:48,D,31821.0,-------
8,9,Sunday Apr 8,TBR,@,BOS,L,7,8,1-8,5,7.0,3:50,D,31979.0,--------
9,10,Monday Apr 9,TBR,@,CHW,W,5,4,2-8,5,6.5,3:47,D,10377.0,+
10,11,Tuesday Apr 10,TBR,@,CHW,W,6,5,3-8,5,6.5,3:44,D,10069.0,++
11,12,Wednesday Apr 11,TBR,@,CHW,L,1,2,3-9,5,6.5,3:02,D,10431.0,-
12,13,Friday Apr 13,TBR,NaN,PHI,L,1,2,3-10,5,8.0,2:53,N,13372.0,--
13,14,Saturday Apr 14,TBR,NaN,PHI,L,4,9,3-11,5,9.0,2:46,N,20934.0,---
14,15,Sunday Apr 15,TBR,NaN,PHI,L,4,10,3-12,5,10.0,3:34,D,19841.0,----
15,16,Monday Apr 16,TBR,NaN,TEX,W,8,4,4-12,5,9.5,2:49,N,9363.0,+
16,17,Tuesday Apr 17,TBR,NaN,TEX,L,2,7,4-13,5,10.5,2:44,N,8972.0,-
17,18,Wednesday Apr 18,TBR,NaN,TEX,W,4,2,5-13,4,10.5,2:36,D,8657.0,+
18,19,Friday Apr 20,TBR,NaN,MIN,W-wo,8,7,6-13,4,11.0,3:30,N,9786.0,++
19,20,Saturday Apr 21,TBR,NaN,MIN,W,10,1,7-13,4,10.0,2:53,N,10106.0,+++
20,21,Sunday Apr 22,TBR,NaN,MIN,W-wo,8,6,8-13,4,9.0,3:39,D,12515.0,++++
21,22,Wednesday Apr 25,TBR,@,BAL,W,8,4,9-13,4,8.5,2:53,N,8730.0,+++++
22,23,Thursday Apr 26,TBR,@,BAL,W,9,5,10-13,4,8.5,3:20,N,9596.0,++++++
23,24,Friday Apr 27,TBR,@,BOS,W,4,3,11-13,4,7.5,3:10,N,32620.0,+++++++
24,25,Saturday Apr 28,TBR,@,BOS,W,12,6,12-13,4,6.5,3:52,D,35795.0,++++++++
25,26,Sunday Apr 29,TBR,@,BOS,L,3,4,12-14,4,7.5,3:01,D,32888.0,-
26,27,Monday Apr 30,TBR,@,DET,W,3,2,13-14,4,7.5,2:52,N,19398.0,+
27,28,Tuesday May 1,TBR,@,DET,L,1,2,13-15,4,7.5,2:28,N,17255.0,-
28,29,Wednesday May 2,TBR,@,DET,L-wo,2,3,13-16,4,8.5,3:28,D,20866.0,--
29,30,Friday May 4,TBR,NaN,TOR,W,6,2,14-16,4,8.0,2:39,N,11117.0,+
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,133,Wednesday Aug 29,TBR,@,ATL,W,8,5,71-62,3,20.5,3:06,N,20876.0,+
133,134,Friday Aug 31,TBR,@,CLE,L,0,3,71-63,3,21.0,2:18,N,25639.0,-
134,135,Saturday Sep 1,TBR,@,CLE,W,5,3,72-63,3,21.0,3:13,N,31816.0,+
135,136,Sunday Sep 2,TBR,@,CLE,W,6,4,73-63,3,20.0,3:10,D,26535.0,++
136,137,Monday Sep 3,TBR,@,TOR,W,7,1,74-63,3,20.0,2:39,N,18034.0,+++
137,138,Tuesday Sep 4,TBR,@,TOR,W,4,0,75-63,3,20.0,2:38,N,17594.0,++++
138,139,Wednesday Sep 5,TBR,@,TOR,L,3,10,75-64,3,21.0,2:42,N,17872.0,-
139,140,Friday Sep 7,TBR,NaN,BAL,W,14,2,76-64,3,20.0,3:05,N,12436.0,+
140,141,Saturday Sep 8,TBR,NaN,BAL,W,10,5,77-64,3,19.0,3:00,N,10275.0,++
141,142,Sunday Sep 9,TBR,NaN,BAL,W,8,3,78-64,3,19.0,2:51,D,13632.0,+++
142,143,Monday Sep 10,TBR,NaN,CLE,W-wo,6,5,79-64,3,18.5,3:38,N,12724.0,++++
143,144,Tuesday Sep 11,TBR,NaN,CLE,L,0,2,79-65,3,19.5,2:44,N,10599.0,-
144,145,Wednesday Sep 12,TBR,NaN,CLE,W,3,1,80-65,3,19.5,2:20,D,10654.0,+
145,146,Friday Sep 14,TBR,NaN,OAK,L,1,2,80-66,3,20.0,3:05,N,11549.0,-
146,147,Saturday Sep 15,TBR,NaN,OAK,W,7,5,81-66,3,20.0,3:19,N,15154.0,+
147,148,Sunday Sep 16,TBR,NaN,OAK,W,5,4,82-66,3,20.0,2:59,D,13197.0,++
148,149,Monday Sep 17,TBR,@,TEX,W,3,0,83-66,3,19.5,2:41,N,21840.0,+++
149,150,Tuesday Sep 18,TBR,@,TEX,W,4,0,84-66,3,18.5,3:04,N,23523.0,++++
150,151,Wednesday Sep 19,TBR,@,TEX,W,9,3,85-66,3,17.5,2:55,D,25168.0,+++++
151,152,Thursday Sep 20,TBR,@,TOR,L-wo,8,9,85-67,3,18.5,3:13,N,19478.0,-
152,153,Friday Sep 21,TBR,@,TOR,W,11,3,86-67,3,18.5,3:20,N,21167.0,+
153,154,Saturday Sep 22,TBR,@,TOR,L,2,5,86-68,3,18.5,2:44,D,27648.0,-
154,155,Sunday Sep 23,TBR,@,TOR,W,5,2,87-68,3,17.5,2:41,D,23944.0,+
155,156,Monday Sep 24,TBR,NaN,NYY,L,1,4,87-69,3,18.5,3:01,N,13832.0,-
156,157,Tuesday Sep 25,TBR,NaN,NYY,L,2,9,87-70,3,19.0,3:14,N,10953.0,--
157,158,Wednesday Sep 26,TBR,NaN,NYY,W,8,7,88-70,3,18.5,3:52,N,11325.0,+
158,159,Thursday Sep 27,TBR,NaN,NYY,L,1,12,88-71,3,19.0,2:49,D,12349.0,-
159,160,Friday Sep 28,TBR,NaN,TOR,L,6,7,88-72,3,19.0,3:39,N,12061.0,--
160,161,Saturday Sep 29,TBR,NaN,TOR,W,4,3,89-72,3,18.0,2:38,N,13221.0,+
161,162,Sunday Sep 30,TBR,NaN,TOR,W,9,4,90-72,3,18.0,3:06,D,13313.0,++